[globalOptions]


# Set the pcrglobwb output directory in an absolute path.
#~ outputDir = MAIN_OUTPUT_DIRECTORY
#~ outputDir = /scratch/depfg/sutan101/watersis_runs_may_2026/test_europe_5km/
outputDir    = /scratch/depfg/sutan101/watersis_runs_may_2026/test_global_6min_with_uly_forcing_2024/
#~ # - on atos
#~ outputDir = /ec/fws4/sb/project/C3SHydroGL/edwin/pgb_watersis_runs_may_2026/europe_5km/

# Set the input directory map in an absolute path . 
#~ inputDir  = /scratch/depfg/sutan101_new/pcrglobwb_input_watersis/develop/europe_5km/
inputDir     = /ec/fws4/sb/project/C3SHydroGL/edwin/pcrglobwb_input_watersis/develop/europe_5km/

# Map of clone (must be provided in PCRaster maps)
cloneMap     = lddsound_06min_version_202007XX_for_ulysses.map

# The area/landmask of interest:
# If None, area/landmask is limited for cells with ldd value. 
landmask     = None
#~ landmask  = /scratch/depfg/sutan101_new/data/watersis_forcing/copied_on_20260303/europe/em_earth/landmask_based_on_pet_hargreaves_samani_day_19700101.nc.map


# netcdf attributes for output files:
institution = Department of Physical Geography, Utrecht University
title       = PCR-GLOBWB 2 output without human factors (naturalized) - version for the WaterSIS project - Europe 5km - MAIN_OUTPUT_DIR
description = by Edwin H. Sutanudjaja (contact: e.h.sutanudjaja@uu.nl)


# starting and end dates
#~ startTime = STARTING_DATE
#~ endTime   = END_DATE
startTime    = 1981-01-01
endTime      = 2022-12-31


#~ # spinning up options:
#~ maxSpinUpsInYears    = NUMBER_OF_SPINUP_YEARS
#~ minConvForSoilSto    = 0.0
#~ minConvForGwatSto    = 0.0
#~ minConvForChanSto    = 0.0
#~ minConvForTotlSto    = 0.0

maxSpinUpsInYears    = 25
minConvForSoilSto    = 0.0
minConvForGwatSto    = 0.0
minConvForChanSto    = 0.0
minConvForTotlSto    = 0.0

# option/directory for saving the spin-up directory 
spinUpOutputDir = True


# By default, run changes the "cwd" to "mapsDir" (inputDir/maps/); Set the following to True to skip this behaviour. 
keep_cwd = True


[meteoOptions]

# Set the forcing temperature and precipitation files
precipitationNC      = /scratch/depfg/sutan101/uly_forcing_files_v2024-02-XX_em-earth_era5land/precipitation_daily_era5land_1981-2022.nc
temperatureNC        = /scratch/depfg/sutan101/uly_forcing_files_v2024-02-XX_em-earth_era5land/tavg_daily_era5land_1981-2022.nc

# Reference potential evaporation using the input file
referenceETPotMethod = Input
refETPotFileNC       = /scratch/depfg/sutan101/uly_forcing_files_v2024-02-XX_em-earth_era5land/pet_daily_era5land_1981-2022.nc

# conversion constants and factors to correct forcing values (optional) so that the units are in m.day-1 and degree Celcius                                                                                                           
precipitationConstant    = 0.0
precipitationFactor      = 0.001
temperatureConstant      = 0.0
temperatureFactor        = 1.0
referenceEPotConstant    = 0.0
referenceEPotFactor      = 0.001 

#~ precipitation_file_per_month     = True
#~ temperature_file_per_month       = True
#~ refETPotFileNC_file_per_month    = True



[landSurfaceOptions]

debugWaterBalance = True

numberOfUpperSoilLayers = 2

# soil and parameters
# - they are used for all land cover types, unless they are are defined in certain land cover type options 
#   (e.g. different/various soil types for agriculture areas)  
topographyNC = topography_parameters_6min_ulysses_v20231130_merged_covered_with_zero.nc
# TODO: You may want to update slopeLength.

# - using soilGrids
soilPropertiesNC        = None
# - if soilPropertiesNC = None, the following soil parameters will be used
firstStorDepth          = 0.30
secondStorDepth         = 1.20
#
soilWaterStorageCap1    = CALC
soilWaterStorageCap2    = CALC
#
poreSizeBeta1           = soilgrids_6min_ulysses_v202311XX/BCH_average_1_global_06min.nc
poreSizeBeta2           = soilgrids_6min_ulysses_v202311XX/BCH_average_2_global_06min.nc
KSat1                   = soilgrids_6min_ulysses_v202311XX/kSat_average_1_global_06min.nc
KSat2                   = soilgrids_6min_ulysses_v202311XX/kSat_average_2_global_06min.nc
airEntryValue1          = soilgrids_6min_ulysses_v202311XX/psiAir_average_1_global_06min.nc
airEntryValue2          = soilgrids_6min_ulysses_v202311XX/psiAir_average_2_global_06min.nc
satVolWC1               = soilgrids_6min_ulysses_v202311XX/vmcSat_average_1_global_06min.nc
satVolWC2               = soilgrids_6min_ulysses_v202311XX/vmcSat_average_2_global_06min.nc
resVolWC1               = 0.0
resVolWC2               = 0.0
#
percolationImp                = global_06min_impeded_drainage_permafrost_nsidc_dsmw_v20231129.nc.map
#
noParameterExtrapolation      = True
landCoverTypes                = forest,grassland
noLandCoverFractionCorrection = False


[forestOptions]

name = forest
debugWaterBalance = True

# snow module properties
snowModuleType      =  Simple
freezingT           =  0.0
degreeDayFactor     =  0.0055
snowWaterHoldingCap =  0.1
refreezingCoeff     =  0.05


landCoverMapsNC   = None
# If NC file is not provided, we have to provide the following pcraster maps:

fracVegCover      = landcovers_v2023-11-XX/vegf_tall.map
minSoilDepthFrac  = landcovers_v2023-11-XX/minf_tall.map
maxSoilDepthFrac  = landcovers_v2023-11-XX/maxf_tall.map
rootFraction1     = landcovers_v2023-11-XX/rfrac1_tall.map
rootFraction2     = landcovers_v2023-11-XX/rfrac2_tall.map
maxRootDepth      = 1.0
# Note: The maxRootDepth is not used for non irrigated land cover type. 	
#
# Parameters for the Arno's scheme:
arnoBeta = None
# If arnoBeta is defined, the soil water capacity distribution is based on this.
# If arnoBeta is NOT defined, maxSoilDepthFrac must be defined such that arnoBeta will be calculated based on maxSoilDepthFrac and minSoilDepthFrac.

cropCoefficientNC = landcovers_v2023-11-XX/tall_crop_coefficient.nc
coverFractionNC   = landcovers_v2023-11-XX/tall_cover_fraction.nc
interceptCapNC    = landcovers_v2023-11-XX/tall_intercept_capacity.nc

# other paramater values
minTopWaterLayer  = 0.0
minCropKC         = 0.2
minInterceptCap   = 0.0002

noParameterExtrapolation = True

# initial conditions:
interceptStorIni = dummy_initial_conditions/interceptStor_forest_1999-12-31.map
snowCoverSWEIni  = dummy_initial_conditions/snowCoverSWE_forest_1999-12-31.map
snowFreeWaterIni = dummy_initial_conditions/snowFreeWater_forest_1999-12-31.map
topWaterLayerIni = dummy_initial_conditions/topWaterLayer_forest_1999-12-31.map
storUppIni       = dummy_initial_conditions/storUpp_forest_1999-12-31.map
storLowIni       = dummy_initial_conditions/storLow_forest_1999-12-31.map
interflowIni     = dummy_initial_conditions/interflow_forest_1999-12-31.map


[grasslandOptions]

name = grassland
debugWaterBalance = True

# snow module properties
snowModuleType      =  Simple
freezingT           =  0.0
degreeDayFactor     =  0.0055
snowWaterHoldingCap =  0.1
refreezingCoeff     =  0.05

landCoverMapsNC   = None
# If NC file is not provided, we have to provide the following pcraster maps:

fracVegCover      = landcovers_v2023-11-XX/vegf_short.map
minSoilDepthFrac  = landcovers_v2023-11-XX/minf_short.map
maxSoilDepthFrac  = landcovers_v2023-11-XX/maxf_short.map
rootFraction1     = landcovers_v2023-11-XX/rfrac1_short.map
rootFraction2     = landcovers_v2023-11-XX/rfrac2_short.map
maxRootDepth      = 0.5
# Note: The maxRootDepth is not used for non irrigated land cover type. 	
#
# Parameters for the Arno's scheme:
arnoBeta = None
# If arnoBeta is defined, the soil water capacity distribution is based on this.
# If arnoBeta is NOT defined, maxSoilDepthFrac must be defined such that arnoBeta will be calculated based on maxSoilDepthFrac and minSoilDepthFrac.

cropCoefficientNC = landcovers_v2023-11-XX/short_crop_coefficient.nc
coverFractionNC   = landcovers_v2023-11-XX/short_cover_fraction.nc
interceptCapNC    = landcovers_v2023-11-XX/short_intercept_capacity.nc

# other paramater values
minTopWaterLayer = 0.0
minCropKC        = 0.2
minInterceptCap  = 0.0002

noParameterExtrapolation = True

# initial conditions:
interceptStorIni = dummy_initial_conditions/interceptStor_grassland_1999-12-31.map
snowCoverSWEIni  = dummy_initial_conditions/snowCoverSWE_grassland_1999-12-31.map
snowFreeWaterIni = dummy_initial_conditions/snowFreeWater_grassland_1999-12-31.map
topWaterLayerIni = dummy_initial_conditions/topWaterLayer_grassland_1999-12-31.map
storUppIni       = dummy_initial_conditions/storUpp_grassland_1999-12-31.map
storLowIni       = dummy_initial_conditions/storLow_grassland_1999-12-31.map
interflowIni     = dummy_initial_conditions/interflow_grassland_1999-12-31.map



[groundwaterOptions]

debugWaterBalance = True

groundwaterPropertiesNC = None

recessionCoeff = recession_coefficient_06min_filled_v20231205_sqrt.map
specificYield  = specific_yield_aquifer_06min_filled_v20231205.map
kSatAquifer    = k_conductivity_aquifer_06min_filled_v20231205.map

# minimum value for groundwater recession coefficient (day-1) 
# - about 11 years
minRecessionCoeff = 0.00025

baseflow_exponent         = 1.5
doNotExtrapolateThickness = True
noParameterExtrapolation  = True

# initial conditions:
storGroundwaterIni                           = dummy_initial_conditions/storGroundwater_1999-12-31.map
storGroundwaterFossilIni                     = dummy_initial_conditions/storGroundwaterFossil_1999-12-31.map
avgNonFossilGroundwaterAllocationLongIni     = dummy_initial_conditions/avgNonFossilGroundwaterAllocationLong_1999-12-31.map
avgNonFossilGroundwaterAllocationShortIni    = dummy_initial_conditions/avgNonFossilGroundwaterAllocationShort_1999-12-31.map
avgTotalGroundwaterAbstractionIni            = dummy_initial_conditions/avgTotalGroundwaterAbstraction_1999-12-31.map
avgTotalGroundwaterAllocationLongIni         = dummy_initial_conditions/avgTotalGroundwaterAllocationLong_1999-12-31.map
avgTotalGroundwaterAllocationShortIni        = dummy_initial_conditions/avgTotalGroundwaterAllocationShort_1999-12-31.map
relativeGroundwaterHeadIni                   = dummy_initial_conditions/relativeGroundwaterHead_1999-12-31.map
baseflowIni                                  = dummy_initial_conditions/baseflow_1999-12-31.map
avgStorGroundwaterIni                        = dummy_initial_conditions/avgStorGroundwater_1999-12-31.map



[routingOptions]

debugWaterBalance = True

# TODO: CHECK CHANNEL LENGTH

# drainage direction map
lddMap           = lddsound_06min_version_202007XX_for_ulysses.map

# cell area (unit: m2)
cellAreaMap      = cellarea.map

# routing method:
routingMethod = accuTravelTime

# manning coefficient
manningsN = 0.04

#~ # Option for flood plain simulation
#~ dynamicFloodPlain = True

# Option for flood plain simulation
dynamicFloodPlain = False

#~ # manning coefficient for floodplain
#~ floodplainManningsN = 0.07


# channel properties for flooding
bankfullCapacity     = None
# - If None, it will be estimated from (bankfull) channel depth (m) and width (m) 


gradient             = gradient_channel_parameters_6min_ulysses_v20231130_merged.nc.map
constantChannelDepth = bankfull_depth_channel_parameters_6min_ulysses_v20231130_merged.nc.map
constantChannelWidth = bankfull_width_channel_parameters_6min_ulysses_v20231130_merged.nc.map
minimumChannelWidth  = bankfull_width_channel_parameters_6min_ulysses_v20231130_merged.nc.map

#~ channelLength     = chanlength.nc.map

# composite crop factors for WaterBodies: 
cropCoefficientWaterNC = cropCoefficientForOpenWater.nc
minCropWaterKC         = 1.00

# lake and reservoir parameters
onlyNaturalWaterBodies = False
waterBodyInputNC       = lakes_and_reservoirs_06min_global_version_july_2020_for_ulysses.nc
# TODO: Update (or remove) this waterBodyInputNC

# initial conditions:
waterBodyStorageIni            = dummy_initial_conditions/waterBodyStorage_1999-12-31.map
channelStorageIni              = dummy_initial_conditions/channelStorage_1999-12-31.map
readAvlChannelStorageIni       = dummy_initial_conditions/readAvlChannelStorage_1999-12-31.map
avgDischargeLongIni            = dummy_initial_conditions/avgDischargeLong_1999-12-31.map
avgDischargeShortIni           = dummy_initial_conditions/avgDischargeShort_1999-12-31.map
m2tDischargeLongIni            = dummy_initial_conditions/m2tDischargeLong_1999-12-31.map
avgBaseflowLongIni             = dummy_initial_conditions/avgBaseflowLong_1999-12-31.map
riverbedExchangeIni            = dummy_initial_conditions/riverbedExchange_1999-12-31.map
subDischargeIni                = dummy_initial_conditions/subDischarge_1999-12-31.map
avgLakeReservoirInflowShortIni = dummy_initial_conditions/avgLakeReservoirInflowShort_1999-12-31.map
avgLakeReservoirOutflowLongIni = dummy_initial_conditions/avgLakeReservoirOutflowLong_1999-12-31.map
timestepsToAvgDischargeIni     = dummy_initial_conditions/timestepsToAvgDischarge_1999-12-31.map



[reportingOptions]

#~ landmask_for_reporting = general/cloneMaps/global_parallelization/mask_M%i.map
landmask_for_reporting    = None

# output files that will be written in the disk in netcdf files:
# - daily resolution
outDailyTotNC = referencePotET,baseflow,directRunoff,interflowTotal,ulysses_rzswi_one_meter,discharge,precipitation,temperature,totalEvaporation
# - monthly resolution
outMonthTotNC = actualET,irrPaddyWaterWithdrawal,irrNonPaddyWaterWithdrawal,domesticWaterWithdrawal,industryWaterWithdrawal,livestockWaterWithdrawal,runoff,totalRunoff,baseflow,directRunoff,interflowTotal,totalGroundwaterAbstraction,desalinationAbstraction,surfaceWaterAbstraction,fossilGroundwaterAbstraction,irrGrossDemand,nonIrrGrossDemand,totalGrossDemand,nonIrrWaterConsumption,nonIrrReturnFlow,precipitation,gwRecharge,surfaceWaterInf,referencePotET,totalEvaporation,totalPotentialEvaporation,totLandSurfaceActuaET,totalLandSurfacePotET,waterBodyActEvaporation,waterBodyPotEvaporation,precipitation_at_irrigation,netLqWaterToSoil_at_irrigation,evaporation_from_irrigation,transpiration_from_irrigation
outMonthAvgNC = discharge,temperature,dynamicFracWat,surfaceWaterStorage,interceptStor,snowFreeWater,snowCoverSWE,topWaterLayer,storUppTotal,storLowTotal,storGroundwater,storGroundwaterFossil,totalWaterStorageThickness,satDegUpp,satDegLow,channelStorage,waterBodyStorage,ulysses_rzswi_one_meter
outMonthEndNC = totalWaterStorageThickness
# - annual resolution
outAnnuaTotNC = totalEvaporation,precipitation,gwRecharge,totalRunoff,baseflow,desalinationAbstraction,surfaceWaterAbstraction,nonFossilGroundwaterAbstraction,fossilGroundwaterAbstraction,totalGroundwaterAbstraction,totalAbstraction,irrGrossDemand,nonIrrGrossDemand,totalGrossDemand,nonIrrWaterConsumption,nonIrrReturnFlow,runoff,actualET,irrPaddyWaterWithdrawal,irrNonPaddyWaterWithdrawal,irrigationWaterWithdrawal,domesticWaterWithdrawal,industryWaterWithdrawal,livestockWaterWithdrawal,precipitation_at_irrigation,netLqWaterToSoil_at_irrigation,evaporation_from_irrigation,transpiration_from_irrigation
outAnnuaAvgNC = temperature,discharge,surfaceWaterStorage,waterBodyStorage,interceptStor,snowFreeWater,snowCoverSWE,topWaterLayer,storUppTotal,storLowTotal,storGroundwater,storGroundwaterFossil,totalWaterStorageThickness,satDegUpp,satDegLow,channelStorage,waterBodyStorage,fractionWaterBodyEvaporation,fractionTotalEvaporation,fracSurfaceWaterAllocation,fracDesalinatedWaterAllocation,gwRecharge,ulysses_rzswi_one_meter
outAnnuaEndNC = surfaceWaterStorage,interceptStor,snowFreeWater,snowCoverSWE,topWaterLayer,storUppTotal,storLowTotal,storGroundwater,storGroundwaterFossil,totalWaterStorageThickness
# - monthly and annual maxima
outMonthMaxNC = channelStorage,dynamicFracWat,floodVolume,floodDepth,surfaceWaterLevel,discharge,totalRunoff,ulysses_rzswi_one_meter
outAnnuaMaxNC = ulysses_rzswi_one_meter

