[globalOptions]

lue_scalability_experiment = True

# Please set the pcrglobwb output directory (outputDir) in an absolute path.
#~ outputDir = MAIN_OUTPUT_DIR
# PLEASE CHANGE TO YOURS
outputDir    = /scratch/depfg/sutan101_new//test_for_toine/africa/


# Set the input directory map in an absolute path. 
# - on eejit
inputDir  = /scratch/depfg/sutan101/data/pcrglobwb_input_arise/develop/
#~ # - on snellius
#~ inputDir     = /projects/0/dfguu/users/edwin/data/pcrglobwb_input_arise/develop/

# Map of clone (must be provided in PCRaster maps)
# PLEASE CHANGE TO YOURS
#~ cloneMap  = global_30sec/cloneMaps/RhineMeuse30sec.clone.map
#~ cloneMap     = /projects/0/dfguu/users/edwin/data/pcrglobwb_input_arise/develop/africa_30sec/cloneMaps/version_2020-XX-XX/mask_uganda_195_basin.map
cloneMap     = /scratch/depfg/sutan101/data/pcrglobwb_input_arise/develop/africa_30sec/cloneMaps/version_2021-05-27/landmask_africa_30sec/landmask_africa_30sec_version_20210527.map


# The area/landmask of interest:
#~ landmask     = /projects/0/dfguu/users/edwin/data/pcrglobwb_input_arise/develop/africa_30sec/cloneMaps/version_2020-XX-XX/mask_uganda_195_basin.map
#~ landmask     = None
landmask     = /scratch/depfg/sutan101/data/pcrglobwb_input_arise/develop/africa_30sec/cloneMaps/version_2021-05-27/landmask_africa_30sec/landmask_africa_30sec_version_20210527.map

# netcdf attributes for output files:
institution = Department of Physical Geography, Utrecht University
title       = PCR-GLOBWB 2 output - test
description = test

# Format: YYYY-MM-DD ; The model runs on daily time step.
#~ startTime = STARTING_DATE
#~ endTime   = END_DATE
startTime = 2000-01-01
endTime   = 2019-12-31

# spinning up options:
#~ maxSpinUpsInYears = NUMBER_OF_SPINUP_YEARS
maxSpinUpsInYears = 0
minConvForSoilSto = 0.0
minConvForGwatSto = 0.0
minConvForChanSto = 0.0
minConvForTotlSto = 0.0

# option/directory for saving the spin-up directory 
spinUpOutputDir = True

log_level_file       = CRITICAL
log_level_console    = CRITICAL
log_level_debug_file = CRITICAL


[meteoOptions]

#~ precipitationNC = /projects/0/dfguu/users/edwin/data/isimip_forcing/isimip3a_version_2021-09-XX/copied_on_2021-09-XX/GSWP3-W5E5/merged/gswp3-w5e5_obsclim_pr_global_daily_1901_2019_version_2021-09-XX.nc
#~ temperatureNC   = /projects/0/dfguu/users/edwin/data/isimip_forcing/isimip3a_version_2021-09-XX/copied_on_2021-09-XX/GSWP3-W5E5/merged/gswp3-w5e5_obsclim_tas_global_daily_1901_2019_version_2021-09-XX.nc

referenceETPotMethod = Input
#~ refETPotFileNC       = /projects/0/dfguu/users/edwin/pcrglobwb_wri_aqueduct_2021_et0_daily_merged/version_2021-09-16_et0_merged/referencePotET_gswp3-w5e5_dailyTot_output_1960-2019.nc

precipitationNC = random, 0.0, 0.1,  0.0,1e99,uniform,random.nc
temperatureNC   = random,25.0,25.0,-1e99,1e99, normal,random.nc
refETPotFileNC  = random, 0.0, 0.1,  0.0,1e99,uniform,random.nc

# variable names in the forcing files
precipitationVariableName = pr
temperatureVariableName   = tas
referenceEPotVariableName = reference_potential_evaporation

# conversion constants and factors to correct forcing values (optional) so that the units are in m.day-1 and degree Celcius                                                                                                           
precipitationConstant    = 0.0
precipitationFactor      = 86.4
temperatureConstant      = -273.15
temperatureFactor        = 1.0
referenceEPotConstant = 0.0
referenceEPotFactor   = 1.0

# initial conditions - dummy - not really required
avgAnnualDiurnalDeltaTempIni = 0.0
avgAnnualPrecipitationIni    = 0.0
avgAnnualTemperatureIni      = 0.0



[landSurfaceOptions]

debugWaterBalance = True

numberOfUpperSoilLayers = 2

# topography parameters
# - they are used for all land cover types, unless they are are defined in certain land cover type options 
#   (e.g. different/various soil types for agriculture areas)  

topographyNC = /scratch/depfg/sutan101_new/pgb_soil_and_topo_30sec_africa_v202102_complete/topography_parameters_30sec_february_2021_africa.nc


soilPropertiesNC = /scratch/depfg/sutan101_new/pgb_soil_and_topo_30sec_africa_v202102_complete/pgb_soil_30sec_africa_v202102_complete.nc

#~ soilPropertiesNC = None
#~ # - if soilPropertiesNC = None, the following soil parameters will be used
#~ firstStorDepth       = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/layerDepth_average_1_africa_30sec.nc
#~ secondStorDepth      = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/layerDepth_average_2_africa_30sec.nc
#~ soilWaterStorageCap1 = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/WHC_average_1_africa_30sec.nc
#~ soilWaterStorageCap2 = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/WHC_average_2_africa_30sec.nc
#~ airEntryValue1       = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/psiAir_average_1_africa_30sec.nc
#~ airEntryValue2       = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/psiAir_average_2_africa_30sec.nc
#~ poreSizeBeta1        = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/BCH_average_1_africa_30sec.nc
#~ poreSizeBeta2        = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/BCH_average_2_africa_30sec.nc
#~ resVolWC1            = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/vmcRes_average_1_africa_30sec.nc
#~ resVolWC2            = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/vmcRes_average_2_africa_30sec.nc
#~ satVolWC1            = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/vmcSat_average_1_africa_30sec.nc
#~ satVolWC2            = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/vmcSat_average_2_africa_30sec.nc
#~ KSat1                = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/kSat_average_1_africa_30sec.nc
#~ KSat2                = africa_30sec/landSurface/soil/soilgrids/version_2021-02-XX/kSat_average_2_africa_30sec.nc
#~ percolationImp       = global_30sec/landSurface/soil/impeded_drainage/global_30sec_impeded_drainage_permafrost_dsmw_correct_lats.nc

# land cover classes
landCoverTypes = naturalVegetationAndRainFedCrops

# we have to correct land cover fractions
noLandCoverFractionCorrection = False

# option to skip extrapolation
noParameterExtrapolation = True


[naturalVegetationAndRainFedCropsOptions]
name = naturalVegetationAndRainFedCrops
debugWaterBalance = True

# snow module properties
snowModuleType      =  Simple
freezingT           =  0.0
degreeDayFactor     =  0.0055
snowWaterHoldingCap =  0.1
refreezingCoeff     =  0.05

# other paramater values
minTopWaterLayer  = 0.0
minCropKC         = 0.2

cropCoefficientNC = africa_30sec/landSurface/landCover/naturalVegetationAndRainFedCrops/version_2020-12-XX/composite-short-n-tall_crop_coefficient.nc
interceptCapNC    = africa_30sec/landSurface/landCover/naturalVegetationAndRainFedCrops/version_2020-12-XX/composite-short-n-tall_intercept_capacity.nc
coverFractionNC   = africa_30sec/landSurface/landCover/naturalVegetationAndRainFedCrops/version_2020-12-XX/composite-short-n-tall_cover_fraction.nc

landCoverMapsNC   = None
# If NC file is not provided, we have to provide the following pcraster maps:
fracVegCover      = 1.0
minSoilDepthFrac  = 0.99
maxSoilDepthFrac  = 1.01
rootFraction1     = africa_30sec/landSurface/landCover/naturalVegetationAndRainFedCrops/version_2020-12-XX/rfrac1_all.nc
rootFraction2     = africa_30sec/landSurface/landCover/naturalVegetationAndRainFedCrops/version_2020-12-XX/rfrac2_all.nc	
maxRootDepth      = africa_30sec/landSurface/landCover/naturalVegetationAndRainFedCrops/version_2020-12-XX/meanrootdepth_all.nc
# Note: The maxRootDepth is not used for non irrigated land cover types. 	
#
# Parameters for the Arno's scheme:
arnoBeta = None
# If arnoBeta is defined, the soil water capacity distribution is based on this.
# If arnoBeta is NOT defined, maxSoilDepthFrac must be defined such that arnoBeta will be calculated based on maxSoilDepthFrac and minSoilDepthFrac.

# initial conditions:
interceptStorIni = 0.0
snowCoverSWEIni  = 0.0
snowFreeWaterIni = 0.0
topWaterLayerIni = 0.0
storUppIni       = 0.0
storLowIni       = 0.0
interflowIni     = 0.0


noParameterExtrapolation = True




[groundwaterOptions]
debugWaterBalance = True

groundwaterPropertiesNC    = None
#
recessionCoeff = 0.1
kSatAquifer    = 0.1
specificYield  = 0.1
#
# minimum value for groundwater recession coefficient (day-1) 
# - about 11 years
minRecessionCoeff = 0.00025
#~ # - about 27 years
#~ minRecessionCoeff = 1.0e-4

# some options for constraining groundwater abstraction
limitFossilGroundWaterAbstraction      = True
estimateOfRenewableGroundwaterCapacity = 0.0
estimateOfTotalGroundwaterThickness    = 1000.
minimumTotalGroundwaterThickness       = 100.
maximumTotalGroundwaterThickness       = None

doNotExtrapolateThickness = True
noParameterExtrapolation  = True



# initial conditions:
storGroundwaterFossilIni                     = 0.0
storGroundwaterIni                           = 0.0
avgNonFossilGroundwaterAllocationLongIni     = 0.0
avgNonFossilGroundwaterAllocationShortIni    = 0.0
avgTotalGroundwaterAbstractionIni            = 0.0
avgTotalGroundwaterAllocationLongIni         = 0.0
avgTotalGroundwaterAllocationShortIni        = 0.0
relativeGroundwaterHeadIni                   = 0.0
baseflowIni                                  = 0.0
avgStorGroundwaterIni                        = 0.0


[routingOptions]
debugWaterBalance = True

# drainage direction map
lddMap = 5

# option to skip lddrepair and lddmask (note: for this, a ldd pcraster map at the clone extent will be needed as the input for "lddMap")
skip_ldd_repair_and_ldd_mask = True

# cell area (unit: m2)
cellAreaMap = 1000000. 

# routing method:
#~ routingMethod = accuTravelTime
routingMethod    = kinematicWave

# maximum number of sub time steps for the kinematic wave
maxiumNumberOfSubTimeSteps = 1

# manning coefficient
manningsN   = 0.04

# Option for flood plain simulation
dynamicFloodPlain = False

# manning coefficient for floodplain
floodplainManningsN = 0.07

# channel gradient
gradient             = 0.001

# constant channel depth 
constantChannelDepth = 2.

# constant channel width (optional)
constantChannelWidth = 20.

# minimum channel width (optional)
minimumChannelWidth  = 20.

# channel properties for flooding
bankfullCapacity     = None
# - If None, it will be estimated from (bankfull) channel depth (m) and width (m) 

# composite crop factors for WaterBodies: 
#~ cropCoefficientWaterNC = global_30min_from_gmd_paper_input/routing/kc_surface_water/cropCoefficientForOpenWater.nc
cropCoefficientWaterNC    = random,0.0,1.0,0.999,1.0,uniform,random.nc
minCropWaterKC            = 1.00


# lake and reservoir parameters
# - set the following None for the LUE experiement
waterBodyInputNC  = None  
fracWaterInp      = None
waterBodyIds      = None
waterBodyTyp      = None
resMaxCapInp      = None
resSfAreaInp      = None
# - this is somehow need to be defined
onlyNaturalWaterBodies = True


#~ # using pre-defined files for water body ids and their outlets (in order to skip the pcraster operations of subcatchment and areaorder)
#~ correct_water_body_outlets = /eejit/depfg/sutan101/data/data_for_lue_test/create_water_bodies_for_lue_test/maps/water_body_outlets_boolean.map
#~ correct_water_body_ids     = /eejit/depfg/sutan101/data/data_for_lue_test/create_water_bodies_for_lue_test/maps/water_body_ids_nominal.map

correct_water_body_outlets = None
correct_water_body_ids     = None


# initial conditions:
waterBodyStorageIni            = 0.0
channelStorageIni              = 0.0
readAvlChannelStorageIni       = 0.0
avgDischargeLongIni            = 0.0
avgDischargeShortIni           = 0.0
m2tDischargeLongIni            = 0.0
avgBaseflowLongIni             = 0.0
riverbedExchangeIni            = 0.0
subDischargeIni                = 0.0
avgLakeReservoirInflowShortIni = 0.0
avgLakeReservoirOutflowLongIni = 0.0
timestepsToAvgDischargeIni     = 0.0



[reportingOptions]

# landmask for reporting
landmask_for_reporting    = None

# output files that will be written in the disk in netcdf files:
# - daily resolution
#~ outDailyTotNC = snowCoverSWE,satDegUpp,satDegLow,discharge,gwRecharge
outDailyTotNC = None
outMonthTotNC = interceptEvap,topWaterLayerEvap,actBareSoilEvap,irrGrossDemand,actTranspiUppTotal,actTranspiLowTotal,directRunoff,interflowTotal,waterBodyActEvaporation,baseflow,surfaceWaterInf,surfaceWaterAbstraction,nonIrrReturnFlow,nonIrrGrossDemand,irrGrossDemand,desalinationAbstraction,fossilGroundwaterAbstraction,nonFossilGroundwaterAbstraction,irrPaddyWaterWithdrawal,irrNonPaddyWaterWithdrawal,domesticWaterWithdrawal,industryWaterWithdrawal,livestockWaterWithdrawal,precipitation,referencePotET
outMonthAvgNC = snowCoverSWE,satDegUpp,satDegLow,discharge,gwRecharge,temperature,snowFreeWater,totalWaterStorageThickness
outMonthEndNC = interceptStor,storUppTotal,storLowTotal,storGroundwaterFossil,surfaceWaterStorage,topWaterLayer,storGroundwater,satDegUpp,satDegLow

#~ # netcdf format and zlib setup
#~ formatNetCDF = NETCDF4
#~ zlib = True
