[globalOptions]
outputDir = MAIN_OUTPUT_DIRECTORY
#~ inputDir = ./
inputDir = /ec/res4/scratch/cyrs/temp_pgb/
cloneMap = input/static/defined_global_landmask_river_and_land_mask_all.map
landmask = input/static/defined_global_landmask_river_and_land_mask_all.map
institution = Department of Physical Geography, Utrecht University
title = PCR-GLOBWB output (not coupled to MODFLOW), version for Ulysses
description = by Edwin H. Sutanudjaja (contact: e.h.sutanudjaja@uu.nl)
startTime = 1981-02-01
endTime = 1981-02-28
maxSpinUpsInYears = 0
minConvForSoilSto = 0.0
minConvForGwatSto = 0.0
minConvForChanSto = 0.0
minConvForTotlSto = 0.0

[meteoOptions]
referenceETPotMethod = Input
precipitationNC = input/meteo/pre.nc
temperatureNC = input/meteo/tavg.nc
refETPotFileNC = input/meteo/pet.nc
precipitationVariableName = pre
temperatureVariableName = tavg
referenceEPotVariableName = pet
precipitationConstant = 0.0
precipitationFactor = 0.001
temperatureConstant = 0.0
temperatureFactor = 1.0
referenceEPotConstant = 0.0
referenceEPotFactor = 0.001
rounddownPrecipitation = False

[landSurfaceOptions]
debugWaterBalance = True
numberOfUpperSoilLayers = 2
topographyNC = input/static/topography_parameters_6min_ulysses_v20231130_merged_covered_with_zero.nc
soilPropertiesNC = None
firstStorDepth = input/static/layerDepth_average_1_global_06min.nc
secondStorDepth = input/static/layerDepth_average_2_global_06min.nc
soilWaterStorageCap1 = input/static/WHC_average_1_global_06min.nc
soilWaterStorageCap2 = input/static/WHC_average_2_global_06min.nc
airEntryValue1 = input/static/psiAir_average_1_global_06min.nc
airEntryValue2 = input/static/psiAir_average_2_global_06min.nc
poreSizeBeta1 = input/static/BCH_average_1_global_06min.nc
poreSizeBeta2 = input/static/BCH_average_2_global_06min.nc
resVolWC1 = input/static/vmcRes_average_1_global_06min.nc
resVolWC2 = input/static/vmcRes_average_2_global_06min.nc
satVolWC1 = input/static/vmcSat_average_1_global_06min.nc
satVolWC2 = input/static/vmcSat_average_2_global_06min.nc
KSat1 = input/static/kSat_average_1_global_06min.nc
KSat2 = input/static/kSat_average_2_global_06min.nc
percolationImp = input/static/global_06min_impeded_drainage_permafrost_nsidc_dsmw_v20231129.nc.map
noParameterExtrapolation = True
landCoverTypes = forest,grassland
noLandCoverFractionCorrection = False

[forestOptions]
name = forest
debugWaterBalance = True
snowModuleType = Simple
freezingT = 0.0
degreeDayFactor = 0.0055
snowWaterHoldingCap = 0.1
refreezingCoeff = 0.05
minTopWaterLayer = 0.0
minCropKC = 0.2
cropCoefficientNC = input/static/tall_crop_coefficient.nc
interceptCapNC = input/static/tall_intercept_capacity.nc
coverFractionNC = input/static/tall_cover_fraction.nc
landCoverMapsNC = None
fracVegCover = input/static/vegf_tall.map
minSoilDepthFrac = input/static/minf_tall.map
maxSoilDepthFrac = input/static/maxf_tall.map
rootFraction1 = input/static/rfrac1_tall.map
rootFraction2 = input/static/rfrac2_tall.map
maxRootDepth = input/static/maxrootdepth_tall.map
noParameterExtrapolation = True
interceptStorIni = input/restart/interceptStor_forest_1981-01-31.map
snowCoverSWEIni = input/restart/snowCoverSWE_forest_1981-01-31.map
snowFreeWaterIni = input/restart/snowFreeWater_forest_1981-01-31.map
topWaterLayerIni = input/restart/topWaterLayer_forest_1981-01-31.map
storUppIni = input/restart/storUpp_forest_1981-01-31.map
storLowIni = input/restart/storLow_forest_1981-01-31.map
interflowIni = input/restart/interflow_forest_1981-01-31.map

[grasslandOptions]
name = grassland
debugWaterBalance = True
snowModuleType = Simple
freezingT = 0.0
degreeDayFactor = 0.0055
snowWaterHoldingCap = 0.1
refreezingCoeff = 0.05
minTopWaterLayer = 0.0
minCropKC = 0.2
cropCoefficientNC = input/static/short_crop_coefficient.nc
interceptCapNC = input/static/short_intercept_capacity.nc
coverFractionNC = input/static/short_cover_fraction.nc
landCoverMapsNC = None
fracVegCover = input/static/vegf_short.map
minSoilDepthFrac = input/static/minf_short.map
maxSoilDepthFrac = input/static/maxf_short.map
rootFraction1 = input/static/rfrac1_short.map
rootFraction2 = input/static/rfrac2_short.map
maxRootDepth = input/static/maxrootdepth_short.map
noParameterExtrapolation = True
interceptStorIni = input/restart/interceptStor_grassland_1981-01-31.map
snowCoverSWEIni = input/restart/snowCoverSWE_grassland_1981-01-31.map
snowFreeWaterIni = input/restart/snowFreeWater_grassland_1981-01-31.map
topWaterLayerIni = input/restart/topWaterLayer_grassland_1981-01-31.map
storUppIni = input/restart/storUpp_grassland_1981-01-31.map
storLowIni = input/restart/storLow_grassland_1981-01-31.map
interflowIni = input/restart/interflow_grassland_1981-01-31.map

[groundwaterOptions]
debugWaterBalance = True
groundwaterPropertiesNC = None
recessionCoeff = input/static/recession_coefficient_06min_filled_v20231205.map
specificYield = input/static/specific_yield_aquifer_06min_filled_v20231205.map
kSatAquifer = input/static/k_conductivity_aquifer_06min_filled_v20231205.map
minRecessionCoeff = 0.00025
baseflow_exponent = 1.5
doNotExtrapolateThickness = True
noParameterExtrapolation = True
storGroundwaterIni = input/restart/storGroundwater_1981-01-31.map
avgStorGroundwaterIni = input/restart/avgStorGroundwater_1981-01-31.map
storGroundwaterFossilIni = 0.0
avgNonFossilGroundwaterAllocationLongIni = 0.0
avgNonFossilGroundwaterAllocationShortIni = 0.0
avgTotalGroundwaterAbstractionIni = 0.0
avgTotalGroundwaterAllocationLongIni = 0.0
avgTotalGroundwaterAllocationShortIni = 0.0
relativeGroundwaterHeadIni = input/restart/relativeGroundwaterHead_1981-01-31.map
baseflowIni = input/restart/baseflow_1981-01-31.map

[routingOptions]
debugWaterBalance = True
lddMap = input/static/lddsound_06min_version_202007XX_for_ulysses.map
cellAreaMap = input/static/cellarea.map
routingMethod = accuTravelTime
manningsN = 0.04
dynamicFloodPlain = False
gradient = input/static/gradient_channel_parameters_6min_ulysses_v20231130_merged.nc.map
constantChannelDepth = input/static/bankfull_depth_channel_parameters_6min_ulysses_v20231130_merged.nc.map
constantChannelWidth = input/static/bankfull_width_channel_parameters_6min_ulysses_v20231130_merged.nc.map
minimumChannelWidth = input/static/bankfull_width_channel_parameters_6min_ulysses_v20231130_merged.nc.map
bankfullCapacity = None
cropCoefficientWaterNC = input/static/cropCoefficientForOpenWater.nc
minCropWaterKC = 1.00
includeWaterBodies = True
waterBodyInputNC = input/static/lakes_and_reservoirs_06min_global_version_july_2020_for_ulysses.nc
onlyNaturalWaterBodies = False
waterBodyStorageIni = input/restart/waterBodyStorage_1981-01-31.map
channelStorageIni = input/restart/channelStorage_1981-01-31.map
readAvlChannelStorageIni = input/restart/readAvlChannelStorage_1981-01-31.map
avgDischargeLongIni = input/restart/avgDischargeLong_1981-01-31.map
avgDischargeShortIni = input/restart/avgDischargeShort_1981-01-31.map
m2tDischargeLongIni = input/restart/m2tDischargeLong_1981-01-31.map
avgBaseflowLongIni = input/restart/avgBaseflowLong_1981-01-31.map
riverbedExchangeIni = input/restart/riverbedExchange_1981-01-31.map
subDischargeIni = input/restart/subDischarge_1981-01-31.map
avgLakeReservoirInflowShortIni = input/restart/avgLakeReservoirInflowShort_1981-01-31.map
avgLakeReservoirOutflowLongIni = input/restart/avgLakeReservoirOutflowLong_1981-01-31.map
timestepsToAvgDischargeIni = input/restart/timestepsToAvgDischarge_1981-01-31.map

[reportingOptions]
landmask_for_reporting = input/static/land_mask_only.map
outDailyTotNC = ulyssesP,ulyssesET,ulyssesSWE,ulyssesQsm,ulyssesQrRunoff,ulyssesDischarge,storLowTotal,storUppTotal
outMonthTotNC = None
outMonthAvgNC = None
outMonthEndNC = None
outAnnuaTotNC = None
outAnnuaAvgNC = None
outAnnuaEndNC = None
outMonthMaxNC = None
outAnnuaMaxNC = None
formatNetCDF = NETCDF4
zlib = True
save_monthly_end_states = True

[prefactorOptions]
log_10_multiplier_for_recessionCoeff = SQUARE_ROOT

[modificationBasedOnSystemArgumentOptions]
-mod = MAIN_OUTPUT_DIRECTORY

